# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(309, 336)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(309, 336))
        Dialog.setMaximumSize(QtCore.QSize(309, 336))
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 100, 251, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.proximal_baude_label = QtWidgets.QLabel(self.groupBox_3)
        self.proximal_baude_label.setGeometry(QtCore.QRect(1, 47, 47, 16))
        self.proximal_baude_label.setObjectName("proximal_baude_label")
        self.proximal_baude = QtWidgets.QLineEdit(self.groupBox_3)
        self.proximal_baude.setGeometry(QtCore.QRect(110, 50, 133, 20))
        self.proximal_baude.setObjectName("proximal_baude")
        self.proximal_com = QtWidgets.QComboBox(self.groupBox_3)
        self.proximal_com.setGeometry(QtCore.QRect(110, 20, 60, 20))
        self.proximal_com.setObjectName("proximal_com")
        self.proximal_com.addItem("")
        self.proximal_com.addItem("")
        self.proximal_com_label = QtWidgets.QLabel(self.groupBox_3)
        self.proximal_com_label.setGeometry(QtCore.QRect(1, 21, 46, 16))
        self.proximal_com_label.setObjectName("proximal_com_label")
        self.roller_dia = QtWidgets.QLineEdit(Dialog)
        self.roller_dia.setGeometry(QtCore.QRect(133, 188, 133, 20))
        self.roller_dia.setObjectName("roller_dia")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 188, 71, 16))
        self.label_7.setObjectName("label_7")
        self.roller_steps = QtWidgets.QLineEdit(Dialog)
        self.roller_steps.setGeometry(QtCore.QRect(133, 214, 133, 20))
        self.roller_steps.setText("")
        self.roller_steps.setObjectName("roller_steps")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 214, 107, 16))
        self.label_8.setObjectName("label_8")
        self.axis_steps = QtWidgets.QLineEdit(Dialog)
        self.axis_steps.setGeometry(QtCore.QRect(133, 266, 133, 20))
        self.axis_steps.setText("")
        self.axis_steps.setObjectName("axis_steps")
        self.axis_pitch = QtWidgets.QLineEdit(Dialog)
        self.axis_pitch.setGeometry(QtCore.QRect(133, 240, 133, 20))
        self.axis_pitch.setObjectName("axis_pitch")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 266, 100, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 240, 73, 16))
        self.label_10.setObjectName("label_10")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 251, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.com_distal_label = QtWidgets.QLabel(self.groupBox_2)
        self.com_distal_label.setGeometry(QtCore.QRect(1, 21, 46, 16))
        self.com_distal_label.setObjectName("com_distal_label")
        self.distal_baude = QtWidgets.QLineEdit(self.groupBox_2)
        self.distal_baude.setGeometry(QtCore.QRect(110, 50, 133, 20))
        self.distal_baude.setObjectName("distal_baude")
        self.distal_baude_label = QtWidgets.QLabel(self.groupBox_2)
        self.distal_baude_label.setGeometry(QtCore.QRect(1, 47, 47, 16))
        self.distal_baude_label.setObjectName("distal_baude_label")
        self.distal_com = QtWidgets.QComboBox(self.groupBox_2)
        self.distal_com.setGeometry(QtCore.QRect(110, 20, 60, 20))
        self.distal_com.setObjectName("distal_com")
        self.distal_com.addItem("")
        self.distal_com.addItem("")
        self.save_parameters = QtWidgets.QPushButton(Dialog)
        self.save_parameters.setGeometry(QtCore.QRect(190, 310, 75, 23))
        self.save_parameters.setObjectName("save_parameters")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_3.setTitle(_translate("Dialog", "Proximal force sensor"))
        self.proximal_baude_label.setText(_translate("Dialog", "Baud rate"))
        self.proximal_com.setItemText(0, _translate("Dialog", "COM11"))
        self.proximal_com.setItemText(1, _translate("Dialog", "COM1"))
        self.proximal_com_label.setText(_translate("Dialog", "COM port"))
        self.label_7.setText(_translate("Dialog", "Roller dia (mm)"))
        self.label_8.setText(_translate("Dialog", "Roller motor steps/rev"))
        self.label_9.setText(_translate("Dialog", "Axis motor steps/rev"))
        self.label_10.setText(_translate("Dialog", "Axis pitch (mm)"))
        self.groupBox_2.setTitle(_translate("Dialog", "Distal force sensor"))
        self.com_distal_label.setText(_translate("Dialog", "COM port"))
        self.distal_baude_label.setText(_translate("Dialog", "Baud rate"))
        self.distal_com.setItemText(0, _translate("Dialog", "COM11"))
        self.distal_com.setItemText(1, _translate("Dialog", "COM1"))
        self.save_parameters.setText(_translate("Dialog", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

