# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters_new_trail.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pynput.mouse import Button, Controller


class Ui_Dialog(object):
    
    def hideSecond(self, Dialog):
        print("i am here")
        Dialog.hide()
        try:
            print(type(Dialog))
        except:
            pass

    def savehide(self, Dialog):
        print("i am here savehide")
        self.hideSecond(Dialog)



    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(447, 376)

        print("main",type(Dialog))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(90, 340, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.roller_dia = QtWidgets.QLineEdit(Dialog)
        self.roller_dia.setGeometry(QtCore.QRect(163, 198, 133, 20))
        self.roller_dia.setObjectName("roller_dia")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(50, 224, 107, 16))
        self.label_8.setObjectName("label_8")
        self.roller_steps = QtWidgets.QLineEdit(Dialog)
        self.roller_steps.setGeometry(QtCore.QRect(163, 224, 133, 20))
        self.roller_steps.setText("")
        self.roller_steps.setObjectName("roller_steps")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(50, 276, 100, 16))
        self.label_9.setObjectName("label_9")

        self.save_parameters = QtWidgets.QPushButton(Dialog, clicked = lambda: self.hideSecond(Dialog))
        # self.save_parameters = QtWidgets.QPushButton(Dialog)
        self.save_parameters.setGeometry(QtCore.QRect(220, 310, 75, 23))
        self.save_parameters.setObjectName("save_parameters")
        
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 20, 251, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.com_distal_label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.com_distal_label_2.setGeometry(QtCore.QRect(1, 21, 61, 16))
        self.com_distal_label_2.setObjectName("com_distal_label_2")
        self.distal_baude_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.distal_baude_2.setGeometry(QtCore.QRect(110, 50, 133, 20))
        self.distal_baude_2.setObjectName("distal_baude_2")
        self.distal_baude_label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.distal_baude_label_2.setGeometry(QtCore.QRect(1, 47, 71, 16))
        self.distal_baude_label_2.setObjectName("distal_baude_label_2")
        self.distal_com_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.distal_com_2.setGeometry(QtCore.QRect(110, 20, 60, 20))
        self.distal_com_2.setObjectName("distal_com_2")
        self.distal_com_2.addItem("")
        self.distal_com_2.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 110, 251, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.proximal_baude_label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.proximal_baude_label_2.setGeometry(QtCore.QRect(1, 47, 81, 16))
        self.proximal_baude_label_2.setObjectName("proximal_baude_label_2")
        self.proximal_baude_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.proximal_baude_2.setGeometry(QtCore.QRect(110, 50, 133, 20))
        self.proximal_baude_2.setObjectName("proximal_baude_2")
        self.proximal_com_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.proximal_com_2.setGeometry(QtCore.QRect(110, 20, 60, 20))
        self.proximal_com_2.setObjectName("proximal_com_2")
        self.proximal_com_2.addItem("")
        self.proximal_com_2.addItem("")
        self.proximal_com_label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.proximal_com_label_2.setGeometry(QtCore.QRect(1, 21, 71, 16))
        self.proximal_com_label_2.setObjectName("proximal_com_label_2")
        self.axis_steps = QtWidgets.QLineEdit(Dialog)
        self.axis_steps.setGeometry(QtCore.QRect(163, 276, 133, 20))
        self.axis_steps.setText("")
        self.axis_steps.setObjectName("axis_steps")
        self.axis_pitch = QtWidgets.QLineEdit(Dialog)
        self.axis_pitch.setGeometry(QtCore.QRect(163, 250, 133, 20))
        self.axis_pitch.setObjectName("axis_pitch")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 198, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(50, 250, 73, 16))
        self.label_10.setObjectName("label_10")

        # self.save_parameters.clicked.connect(self.savehide)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_8.setText(_translate("Dialog", "Roller motor steps/rev"))
        self.label_9.setText(_translate("Dialog", "Axis motor steps/rev"))
        self.save_parameters.setText(_translate("Dialog", "Save"))
        self.groupBox_2.setTitle(_translate("Dialog", "Distal force sensor"))
        self.com_distal_label_2.setText(_translate("Dialog", "COM port"))
        self.distal_baude_label_2.setText(_translate("Dialog", "Baud rate"))
        self.distal_com_2.setItemText(0, _translate("Dialog", "COM11"))
        self.distal_com_2.setItemText(1, _translate("Dialog", "COM1"))
        self.groupBox_3.setTitle(_translate("Dialog", "Proximal force sensor"))
        self.proximal_baude_label_2.setText(_translate("Dialog", "Baud rate"))
        self.proximal_com_2.setItemText(0, _translate("Dialog", "COM11"))
        self.proximal_com_2.setItemText(1, _translate("Dialog", "COM1"))
        self.proximal_com_label_2.setText(_translate("Dialog", "COM port"))
        self.label_7.setText(_translate("Dialog", "Roller dia (mm)"))
        self.label_10.setText(_translate("Dialog", "Axis pitch (mm)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
